const items = [
    { itemcode: "B1001", itemtype:"Burger", itemname: "Classic Burger (Large)", image: "", price: 750.00, discount: 0 },
    { itemcode: "B1002", itemtype:"Burger", itemname: "Classic Burger (Regular)", image: "", price: 1500.00, discount: 15 },
    { itemcode: "B1003", itemtype:"Burger", itemname: "Turkey Burger", image: "", price: 1600.00, discount: 0 },
    { itemcode: "B1004", itemtype:"Burger", itemname: "Chicken Burger (Large)", image: "", price: 1400.00, discount: 0 },
    { itemcode: "B1005", itemtype:"Burger", itemname: "Chicken Burger (Regular)", image: "", price: 800.00, discount: 20 },
    { itemcode: "B1006", itemtype:"Burger", itemname: "Cheese Burger (Large)", image: "", price: 1000.00, discount: 0 },
    { itemcode: "B1007", itemtype:"Burger", itemname: "Cheese Burger (Regular)", image: "", price: 600.00, discount: 0 },
    { itemcode: "B1008", itemtype:"Burger", itemname: "Bacon Burger", image: "", price: 650.00, discount: 15 },
    { itemcode: "B1009", itemtype:"Burger", itemname: "Shawarma Burger", image: "", price: 800.00, discount: 0 },
    { itemcode: "B1010", itemtype:"Burger", itemname: "Olive Burger", image: "", price: 1800.00, discount: 0 },
    { itemcode: "B1012", itemtype:"Burger", itemname: "Double-Cheese Burger", image: "", price: 1250.00, discount: 20 },
    { itemcode: "B1013", itemtype:"Burger", itemname: "Crispy Chicken Burger (Regular)", image: "", price: 1200.00, discount: 0 },
    { itemcode: "B1014", itemtype:"Burger", itemname: "Crispy Chicken Burger (Large)", image: "", price: 1600.00, discount: 10 },
    { itemcode: "B1015", itemtype:"Burger", itemname: "Paneer Burger", image: "", price: 900.00, discount: 0 },
    { itemcode: "B1016", itemtype:"Submarine", itemname: "Crispy Chicken Submarine (Large)", image: "", price: 2000.00, discount: 0 },
    { itemcode: "B1017", itemtype:"Submarine", itemname: "Crispy Chicken Submarine (Regular)", image: "", price: 1500.00, discount: 0 },
    { itemcode: "B1018", itemtype:"Submarine", itemname: "Chicken Submarine (Large)", image: "", price: 1800.00, discount: 3 },
    { itemcode: "B1019", itemtype:"Submarine", itemname: "Chicken Submarine (Regular)", image: "", price: 1400.00, discount: 0 },
    { itemcode: "B1020", itemtype:"Submarine", itemname: "Grinder Submarine", image: "", price: 2300.00, discount: 0 },
    { itemcode: "B1021", itemtype:"Submarine", itemname: "Cheese Submarine", image: "", price: 2200.00, discount: 0 },
    { itemcode: "B1022", itemtype:"Submarine", itemname: "Double Cheese n Chicken Submarine", image: "", price: 1900.00, discount: 16 },
    { itemcode: "B1023", itemtype:"Submarine", itemname: "Special Horgie Submarine", image: "", price: 2800.00, discount: 0 },
    { itemcode: "B1024", itemtype:"Submarine", itemname: "MOS Special Submarine", image: "", price: 3000.00, discount: 0 },
    { itemcode: "B1025", itemtype:"Fries", itemname: "Steak Fries (Large)", image: "", price: 1200.00, discount: 0 },
    { itemcode: "B1026", itemtype:"Fries", itemname: "Steak Fries (Medium)", image: "", price: 600.00, discount: 0 },
    { itemcode: "B1027", itemtype:"Fries", itemname: "French Fries (Large)", image: "", price: 800.00, discount: 0 },
    { itemcode: "B1028", itemtype:"Fries", itemname: "French Fries (Medium)", image: "", price: 650.00, discount: 0 },
    { itemcode: "B1029", itemtype:"Fries", itemname: "French Fries (Small)", image: "", price: 450.00, discount: 0 },
    { itemcode: "B1030", itemtype:"Fries", itemname: "Sweet Potato Fries (Large)", image: "", price: 600.00, discount: 0 },
    { itemcode: "B1031", itemtype:"Pasta", itemname: "Chicken n Cheese Pasta", image: "", price: 1600.00, discount: 15 },
    { itemcode: "B1032", itemtype:"Pasta", itemname: "Chicken Penne Pasta", image: "", price: 1700.00, discount: 0 },
    { itemcode: "B1033", itemtype:"Pasta", itemname: "Ground Turkey Pasta Bake", image: "", price: 2900.00, discount: 10 },
    { itemcode: "B1034", itemtype:"Pasta", itemname: "Creamy Shrimp Pasta", image: "", price: 2000.00, discount: 0 },
    { itemcode: "B1035", itemtype:"Pasta", itemname: "Lemon Butter Pasta", image: "", price: 1950.00, discount: 0 },
    { itemcode: "B1036", itemtype:"Pasta", itemname: "Tagliatelle Pasta", image: "", price: 2400.00, discount: 1 },
    { itemcode: "B1037", itemtype:"Pasta", itemname: "Baked Ravioli", image: "", price: 2000.00, discount: 1 },
    { itemcode: "B1038", itemtype:"Chicken", itemname: "Fried Chicken (Small)", image: "", price: 1200.00, discount: 0 },
    { itemcode: "B1039", itemtype:"Chicken", itemname: "Fried Chicken (Regular)", image: "", price: 2300.00, discount: 10 },
    { itemcode: "B1040", itemtype:"Chicken", itemname: "Fried Chicken (Large)", image: "", price: 3100.00, discount: 5 },
    { itemcode: "B1041", itemtype:"Chicken", itemname: "Hot Wings (Large)", image: "", price: 2400.00, discount: 0 },
    { itemcode: "B1042", itemtype:"Chicken", itemname: "Devilled Chicken (Large)", image: "", price: 900.00, discount: 0 },
    { itemcode: "B1043", itemtype:"Chicken", itemname: "BBQ Chicken (Regular)", image: "", price: 2100.00, discount: 0 },
    { itemcode: "B1044", itemtype:"Drinks", itemname: "Pepsi (330ml)", image: "", price: 990.00, discount: 5 },
    { itemcode: "B1045", itemtype:"Drinks", itemname: "Coca-Cola (330ml)", image: "", price: 1230.00, discount: 0 },
    { itemcode: "B1046", itemtype:"Drinks", itemname: "Sprite (330ml)", image: "", price: 1500.00, discount: 3 },
    { itemcode: "B1047", itemtype:"Drinks", itemname: "Mirinda (330ml)", image: "", price: 850.00, discount: 7 }
  ];
  

export default items;